/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SmallSpaceFighter({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/SmallSpaceFighter.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-6.36, 7.45, 5.74]} rotation={[-1.4, 0.66, 2.35]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[6.61, 6.54, -4.14]} rotation={[-1.16, -0.51, -0.7]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['HullPlain.002']} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['HullColor.002']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['CockpitGlass.002']} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Engine.002']} />
    </group>
  )
}

useGLTF.preload('/models/SmallSpaceFighter.glb')
